# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_use_quantity', models.IntegerField()),
                ('item_barcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('vendor_email', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Vendor'),
        ),
    ]
