# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Vendor')),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='friday_time',
            field=models.TimeField(blank=True, verbose_name='Friday Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='monday_time',
            field=models.TimeField(blank=True, verbose_name='Monday Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='saturday_time',
            field=models.TimeField(blank=True, verbose_name='Saturday Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sunday_time',
            field=models.TimeField(blank=True, verbose_name='Sunday Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='thursday_time',
            field=models.TimeField(blank=True, verbose_name='Thursday Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='tuesday_time',
            field=models.TimeField(blank=True, verbose_name='Tuesday Time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='wednesday_time',
            field=models.TimeField(blank=True, verbose_name='Wednesday Time'),
        ),
    ]
