# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160626_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_order_point',
            field=models.IntegerField(default=0),
        ),
    ]
