# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_item_order_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_max_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
